# Site settings
title: Alexander Thiemann
email: mail@athiemann.net
description: >
  (functional) programming and more
baseurl: ""
url: "http://athiemann.net"
twitter_username: agrafix
github_username:  agrafix

exclude: [vendor, Gemfile, .travis.yml]

# Build settings
markdown: kramdown

kramdown:
    input: GFM
